create extension if not exists pgcrypto;
create table if not exists public.allowed_users (email text primary key, created_at timestamptz not null default now());
alter table public.allowed_users enable row level security;
create or replace function public.is_allowed_user() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.allowed_users where lower(email) = lower(auth.jwt() ->> 'email')) $$;
create table if not exists public.jobs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, company text not null default '', role text not null default '', url text, jd text not null default '', source text not null default '', location text not null default '', work_mode text not null default '', employment_type text not null default '', attendance text not null default '', match_score smallint not null default 0 check (match_score between 0 and 100), eligibility text not null default 'review', captured_at timestamptz not null default now(), deadline timestamptz, updated_at timestamptz not null default now());
create unique index if not exists jobs_user_url_unique on public.jobs(user_id, url) where url is not null and url <> '';
create table if not exists public.applications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, job_id uuid references public.jobs(id) on delete set null, stage text not null default 'discovered', review_status text not null default 'pending', apply_method text not null default 'form', referral_code text not null default '', referral_source text not null default '', data jsonb not null default '{}'::jsonb, applied_at timestamptz, followup_at timestamptz, outcome text not null default '', updated_at timestamptz not null default now());
create index if not exists applications_user_updated_idx on public.applications(user_id, updated_at desc);
create table if not exists public.application_materials (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, application_id uuid not null references public.applications(id) on delete cascade, material_type text not null, language text not null default 'auto', version integer not null default 1, content text not null default '', storage_path text, generation_basis jsonb not null default '{}'::jsonb, review_status text not null default 'pending', updated_at timestamptz not null default now());
create table if not exists public.application_answers (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, application_id uuid not null references public.applications(id) on delete cascade, question text not null, answer text not null default '', evidence_source text not null default '', confirmed boolean not null default false, updated_at timestamptz not null default now());
create table if not exists public.interview_prep (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, application_id uuid not null references public.applications(id) on delete cascade, public_sources jsonb not null default '[]'::jsonb, inferred_questions jsonb not null default '[]'::jsonb, deep_dive jsonb not null default '[]'::jsonb, mock_plan text not null default '', debrief text not null default '', updated_at timestamptz not null default now());
create table if not exists public.source_inbox (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, source_type text not null, source_url text, raw_text text not null default '', referral_code text not null default '', confidence numeric(3,2) not null default 0 check (confidence between 0 and 1), processed_at timestamptz, created_at timestamptz not null default now());

alter table public.jobs enable row level security; alter table public.applications enable row level security; alter table public.application_materials enable row level security; alter table public.application_answers enable row level security; alter table public.interview_prep enable row level security; alter table public.source_inbox enable row level security;
create policy "owner jobs" on public.jobs for all using (public.is_allowed_user() and auth.uid() = user_id) with check (public.is_allowed_user() and auth.uid() = user_id);
create policy "owner applications" on public.applications for all using (public.is_allowed_user() and auth.uid() = user_id) with check (public.is_allowed_user() and auth.uid() = user_id);
create policy "owner materials" on public.application_materials for all using (public.is_allowed_user() and auth.uid() = user_id) with check (public.is_allowed_user() and auth.uid() = user_id);
create policy "owner answers" on public.application_answers for all using (public.is_allowed_user() and auth.uid() = user_id) with check (public.is_allowed_user() and auth.uid() = user_id);
create policy "owner interview" on public.interview_prep for all using (public.is_allowed_user() and auth.uid() = user_id) with check (public.is_allowed_user() and auth.uid() = user_id);
create policy "owner inbox" on public.source_inbox for all using (public.is_allowed_user() and auth.uid() = user_id) with check (public.is_allowed_user() and auth.uid() = user_id);

insert into storage.buckets (id, name, public) values ('application-files', 'application-files', false) on conflict (id) do update set public = false;
create policy "owner private files" on storage.objects for all using (public.is_allowed_user() and bucket_id = 'application-files' and (storage.foldername(name))[1] = auth.uid()::text) with check (public.is_allowed_user() and bucket_id = 'application-files' and (storage.foldername(name))[1] = auth.uid()::text);
alter table public.applications replica identity full;
do $$ begin alter publication supabase_realtime add table public.applications; exception when duplicate_object then null; end $$;
